spring.application.name=expense-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/expense
spring.datasource.username=postgres
spring.datasource.password=1566
spring.jpa.hibernate.ddl-auto=update